import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google"; // Добавлен Roboto
import "./globals.css";
import { ChildProps } from "@/types";
import UiProvider from "@/components/providers/ui-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "E commerse web store",
    description: "Buy and sail your products with this platform"
  }
};

export default function RootLayout({ children }: ChildProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <UiProvider>
          {children}
        </UiProvider>
      </body>
    </html>
  );
}
